spring:
  datasource:
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S11P22A106?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S11P22A106
    password: abuba106
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update


  servlet:
    multipart:
      enabled: true
      max-request-size: 300MB
      max-file-size: 50MB

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    bucket-name: hexagon-abuba
    region: ap-northeast-2


