spring:
  application:
    name: abuba
  profiles:
    active: prod
  jwt:
    secret: spring.jwt.secret=vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    hikari:
      maximum-pool-size: 20  # 원하는 최대 연결 수로 변경
      minimum-idle: 5        # 최소 유휴 연결 수
      idle-timeout: 30000    # 유휴 연결 타임아웃 (밀리초)
      connection-timeout: 30000 # 연결 대기 타임아웃 (밀리초)

springdoc:
  swagger-ui:
    path: /swagger # Swagger UI를 표시할 커스텀 경로
  api-docs:
    path: /docs  # API 문서 경로를 커스텀

accountNo1: 0010307956085451
accountNo2: 0017126350155275

api:
  key: 50f3e70a64074c42a5905b877ea1b194
user:
  key: 53714417-7f2c-4bed-8608-f7d39353bbd9
#security log
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.authentication: DEBUG
