spring:
  application:
    name: abuba
  profiles:
      active: prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    hikari:
      maximum-pool-size: 1000  # 원하는 최대 연결 수로 변경
      minimum-idle: 10        # 최소 유휴 연결 수
      idle-timeout: 3600    # 유휴 연결 타임아웃 (second)
      connection-timeout: 3600 # 연결 대기 타임아웃 (second)

#actuactor
management:
  endpoints:
    web:
      exposure:
        include: health, metrics
springdoc:
  swagger-ui:
    path: /swagger # Swagger UI를 표시할 커스텀 경로
  api-docs:
    path: /docs  # API 문서 경로를 커스텀

#security log
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.authentication: DEBUG

